Database:
  user: PGUSER
  password: PGPASS
  host: PG_HOST
  port: PG_PORT
  database: PG_DATABASE
  max: PG_MAX_CONNECTIONS
  min: PG_MIN_CONNECTIONS
Protocol:
  frontend_base_suburl: FRONTEND_BASE_URL
ExternalServer:
  port: SERVER_PORT
  enableGlobalRateLimit: ENABLE_GLOBAL_RATE_LIMIT
  globalRateLimit:
    window: GLOBAL_RATE_LIMIT_WINDOW_IN_MILLISECONDS
    hits: GLOBAL_RATE_LIMIT_HITS_PER_WINDOW
  cors:
    allowedOrigins: ALLOWED_URLS
auth-service:
  url: AUTH_SERVICE_INTERNAL


L1:
  chainId: L1_CHAIN_ID
  name: L1_NAME
  rpcUrl: L1_RPC_URL
  iconUrl: L1_ICON_URL
  explorer: L1_EXPLORER
  explorerUrl: L1_EXPLORER_URL
  optimismPortalProxy: L1_PROXY
  currency: L1_CURRENCY
  currencySymbol: L1_CURRENCY_SYMBOL

L2:
  chainId: L2_CHAIN_ID
  name: L2_NAME
  rpcUrl: L2_RPC_URL
  iconUrl: L2_ICON_URL
  explorer: L2_EXPLORER
  explorerUrl: L2_EXPLORER_URL
  l2ToL1MessagePasserProxy: L2_TO_L1_MESSAGE_PROXY
  l2OutputOracleProxy: L2_PROXY
  currency: L2_CURRENCY
  currencySymbol: L2_CURRENCY_SYMBOL

TOKEN:
  name: TOKEN_NAME
  symbol: TOKEN_SYMBOL
  contractAddress: TOKEN_CONTRACT_ADDRESS
  iconUrl: TOKEN_ICON_URL
