ExternalServer:
  port: 3009
  enableGlobalRateLimit: true
  headerCtMaxAge: 86400
  numberOfProxies: 2
  cors:
    allowedOrigins:
      - '["http://localhost"]'
  requestBodySize: 1mb
logger:
  level: "debug"

Database:
  max: 20
  min: 5
