ExternalServer:
  port: 3009
  enableGlobalRateLimit: true
  headerCtMaxAge: 86400
  numberOfProxies: 2
  cors:
    allowedOrigins:
      - '["http://localhost:5173"]'
  requestBodySize: 1mb
logger:
  level: "debug"

Database:
  max: 20
  min: 5
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  database: bridge

L1:
  chainId: 11155111
  name: Sepolia
  rpcUrl: https://testing-sepolia-testnet.zeeve.net/IsL4JRvcCOuJilvuv8Mj/rpc
  iconUrl: https://app.nfts2me.com/assets/chainlist/holesky.png
  explorer: Etherscan
  explorerUrl: https://sepolia.etherscan.io
  optimismPortalProxy: "0x91Cccb6fF2d561a3DC71c6072C23dA6055622cdD"
  l2OutputOracleProxy: "0x9CBE095A6fAeA0186c44F95701b9d1d2e329a58a"
  currency: Ethereum
  currencySymbol: ETH
 
L2:
  chainId: 625
  name: OP Chain
  rpcUrl: https://sequencer.rpc.bnry.testnet.zeeve.net/
  iconUrl: https://cryptologos.cc/logos/optimism-ethereum-op-logo.png
  explorer: Blockscout
  explorerUrl: https://bnry.testnet.explorer.zeeve.net/
  l2ToL1MessagePasserProxy: "0x4200000000000000000000000000000000000016"
  currency: Test BNRY
  currencySymbol: TBNRY
  finalizationPeriod: 12
 
TOKEN:
  name: Test BNRY
  symbol: TBNRY
  contractAddress: "0x46d878bf7BF62Ec542953CB89Ac0bF58d991181e"
  iconUrl: https://cryptologos.cc/logos/optimism-ethereum-op-logo.png